import {
	bc,
	bh,
	bp,
	br,
	brn,
	bt,
	bs,
	be,
	bn,
	proj1,
	proj13,
	proj14,
	proj15,
	proj16,
	proj17,
	proj2,
	proj3,
	proj4,
	proj5,
	proj6,
	proj7,
	afterdark,
	endless,
	intro,
	love,
	mareux,
	trench,
} from '../assets/imgs'

export const about = {
	header: "Hi, I'm Steven Bouldin.",
	info: `I'm a Computer Engineer and Fullstack Developer specializing in AI and autonomous systems. I have extensive experience developing web applications, AI frameworks, and 3D interactive experiences. I enjoy combining cutting-edge technology with creative solutions to solve complex problems. My work spans from local AI implementations to fully autonomous agents, always pushing the boundaries of what's possible with modern technology.`,
	github: 'https://github.com/Sacred-G',
	gmail: 'steven@sacred-g.com',
	phone: '310-756-5444',
	exp: [
		{
			title: 'Computer Information Systems',
			text: 'Auburn University - Football Scholarship',
		},
		{
			title: 'Software Engineer & Co-Founder',
			text: 'JFSB Consulting',
		},
		{
			title: 'AI Systems Engineer',
			text: 'Independent AI Development',
		},
		{
			title: 'Fullstack Developer',
			text: 'Centered Support Service',
		},
		{
			title: 'Software Engineer',
			text: 'Apple Inc',
		},
		{
			title: 'IT Director & Software Engineer',
			text: 'JFC Technology',
		},
	],
}

export const projects = [
	{
		title: "3D Portfolio",
		info: 'Interactive 3D Portfolio Website',
		techs: 'three.js react.js typescript blender',
		text: 'A fully interactive 3D portfolio website built with React Three Fiber and Blender. Features animated 3D models, interactive scenes, sound effects, and a fillable invoice system. Combines the power of Blender 3D modeling with Three.js for an immersive web experience.',
		github: 'https://github.com/Sacred-G/3d-portfolio',
		img1: bt,
		img2: proj1,
	},
	{
		title: 'AgenticSeek',
		info: 'Fully Local AI Assistant',
		techs: 'python ai machine-learning local-ai',
		text: 'A fully local Manus AI implementation that requires no APIs and no monthly bills. Enjoy an autonomous agent that thinks, browses the web, and codes for the sole cost of electricity. Complete privacy and control over your AI assistant.',
		github: 'https://github.com/Sacred-G/agenticSeek-sb',
		img1: bs,
		img2: proj16,
	},
	{
		title: 'AI Collection',
		info: 'Multi-Model AI Platform',
		techs: 'python streamlit openai gemini llama',
		text: 'AI ALL IN ONE platform with chat capabilities for Excel, PDF, and documents. Features GPT-4 Assistant, DALL-E & Gemini/Gemini Pro Vision, LLAMA, and BAIDU integration using Streamlit for a comprehensive AI experience.',
		github: 'https://github.com/Sacred-G/AI_COLLECTION',
		img1: bn,
		img2: proj17,
	},
	{
		title: 'Agent Zero',
		info: 'AI Framework',
		techs: 'python ai autonomous-agents',
		text: 'Agent Zero AI framework - A comprehensive framework for building autonomous AI agents with advanced reasoning and decision-making capabilities.',
		github: 'https://github.com/Sacred-G/agent-zero',
		img1: bt,
		img2: proj13,
	},
	{
		title: 'AI Chatbot Suite',
		info: 'Multi-Modal Chat System',
		techs: 'python openai memory postgresql',
		text: 'Complete chatbot system supporting PDF Chatbot, Image Chatbot, and Web-Site Chatbot with knowledge base. Integrates OpenAI, memory management, and PostgreSQL for persistent storage.',
		github: 'https://github.com/Sacred-G/ai',
		img1: be,
		img2: proj15,
	},
	{
		title: 'BrainWave',
		info: 'SaaS AI Landing Page',
		techs: 'react.js typescript animations',
		text: 'Modern animated SaaS Generative AI landing page with smooth animations and contemporary design. Built to showcase AI products with engaging user experience.',
		github: 'https://github.com/Sacred-G/BrainWave',
		img1: br,
		img2: proj2,
	},
	{
		title: 'Commerce Platform',
		info: 'Full Auction Application',
		techs: 'django sqlite3 stripe paypal',
		text: 'Complete commerce auction application with Django, SQLite3, and Stripe/PayPal payments. Features user-to-user messaging and responsive design for seamless trading experience.',
		github: 'https://github.com/Sacred-G/commerce',
		img1: bp,
		img2: proj3,
	},
	{
		title: 'Contract Management',
		info: 'Document Processing System',
		techs: 'python ms-word excel gui',
		text: 'Python program that pulls data from MS Word documents and summarizes information into Excel sheets with GUI interface. Can convert .doc files to .docx for compatibility with older documents.',
		github: 'https://github.com/Sacred-G/ContractManagement',
		img1: br,
		img2: proj14,
	},
	{
		title: 'ChiefOnboarding',
		info: 'Employee Onboarding Platform',
		techs: 'slack web portal employee-management',
		text: 'Free and open-source employee onboarding platform. Onboard new hires through Slack integration or web portal. Streamlines the hiring process with automated workflows.',
		github: 'https://github.com/Sacred-G/ChiefOnboarding',
		img1: brn,
		img2: proj4,
	},
	{
		title: 'ChatGPT AutoPilot',
		info: 'Autonomous GPT-4 Agent',
		techs: 'openai function-calling autonomous',
		text: 'GPT Auto-pilot that uses function calling to build whatever you can describe or edit existing apps. Inspired by unconventional coding approaches for maximum flexibility and creativity.',
		github: 'https://github.com/Sacred-G/chatgpt-autopilot',
		img1: bh,
		img2: proj5,
	},
	{
		title: 'Anthropic Cookbook',
		info: 'Claude AI Recipes',
		techs: 'anthropic claude notebooks',
		text: 'A collection of notebooks and recipes showcasing fun and effective ways of using Claude AI. Demonstrates various techniques and patterns for working with Anthropic models.',
		github: 'https://github.com/Sacred-G/anthropic-cookbook',
		img1: bc,
		img2: proj6,
	},
	{
		title: 'AutoAI',
		info: 'Autonomous GPT-4 System',
		techs: 'openai gpt-4 autonomous experimental',
		text: 'An experimental open-source attempt to make GPT-4 fully autonomous. Pushes the boundaries of what\'s possible with current AI technology for independent operation.',
		github: 'https://github.com/Sacred-G/autoai',
		img1: brn,
		img2: proj7,
	},
]

export const musics = [
	{
		title: 'Intro',
		singer: 'Welcome',
		img: intro,
	},
	{
		title: 'After Dark',
		singer: 'Mr. Kitty',
		img: afterdark,
	},
	{
		title: 'Bandito',
		singer: 'Twenty One Pilots',
		img: trench,
	},
	{
		title: 'The Perfect Girl',
		singer: 'Mareux',
		img: mareux,
	},
	{
		title: "Can't Help Falling In Love",
		singer: 'Twenty One Pilots',
		img: love,
	},
	{
		title: 'Endless Song',
		singer: 'Aaron',
		img: endless,
	},
]

export const screens = {
	s1: ['light_pic1', 'light_pic2', 'light_pic3', 'light_pic13'],
	s2: ['light_pic4', 'light_pic5', 'light_pic6', 'light_pic13'],
	s3: ['light_pic7', 'light_pic8', 'light_pic9', 'light_pic13'],
	s4: ['light_pic10', 'light_pic11', 'light_pic12', 'light_pic13'],
}
